import { useEffect, useMemo, useState } from "react";
import { Background, Controls, MarkerType, MiniMap, ReactFlow } from "@xyflow/react";
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import "./VisualRenderer.css";

function usePlayback(length) {
  const [step, setStep] = useState(0); const [playing, setPlaying] = useState(false);
  useEffect(() => { if (!playing || length < 2) return undefined; const timer = window.setInterval(() => setStep((value) => value >= length - 1 ? 0 : value + 1), 1200); return () => window.clearInterval(timer); }, [playing, length]);
  return { step, setStep, playing, setPlaying };
}
function Player({ state, length }) { return <div className="visual-player"><button type="button" onClick={() => state.setStep(Math.max(0, state.step - 1))} disabled={state.step === 0}>←</button><button type="button" onClick={() => state.setPlaying((value) => !value)}>{state.playing ? "Pause" : "Play"}</button><button type="button" onClick={() => state.setStep(Math.min(length - 1, state.step + 1))} disabled={state.step === length - 1}>→</button><span>{state.step + 1} / {length}</span></div>; }

function Algorithm({ spec }) {
  const state = usePlayback(spec.steps.length); const current = spec.steps[state.step] || {}; const values = current.values?.length ? current.values : spec.data?.values || [2, 5, 8, 12, 16, 23, 38]; const numeric = values.map((value) => Number(value) || 1); const active = new Set(current.active_indices || []);
  return <div className="algorithm-lab"><div className="array-stage">{values.map((value, index) => <button type="button" className={active.has(index) ? "is-active" : ""} onClick={() => state.setStep(Math.min(index, spec.steps.length - 1))} key={`${value}-${index}`}><i style={{ height: `${32 + (numeric[index] / Math.max(...numeric, 1)) * 80}px` }} /><strong>{value}</strong><small>{index}</small></button>)}</div><div className="stage-caption"><strong>{current.title}</strong><span>{current.description}</span></div><Player state={state} length={spec.steps.length} /></div>;
}
function Process({ spec }) { const state = usePlayback(spec.steps.length); return <div className="process-lab"><div className="process-track">{spec.steps.map((item, index) => <button type="button" onClick={() => state.setStep(index)} className={index === state.step ? "is-active" : index < state.step ? "is-done" : ""} key={`${item.title}-${index}`}><i>{index + 1}</i><strong>{item.title}</strong><span>{item.description}</span></button>)}</div><Player state={state} length={spec.steps.length} /></div>; }

function NetworkCanvas({ spec, tree = false }) {
  const [selected, setSelected] = useState(null);
  const nodes = useMemo(() => spec.nodes.map((node, index) => ({ id: node.id, data: { label: node.label, description: node.description }, position: { x: node.x ?? (tree ? 280 + (index % 4 - 1.5) * 170 : 30 + (index % 3) * 250), y: node.y ?? (tree ? 25 + Math.floor(Math.log2(index + 1)) * 130 : 25 + Math.floor(index / 3) * 140) }, style: { background: tree ? "#173b2c" : "#18342b", border: `1px solid ${tree ? "#75ad8d" : "#df9a62"}`, borderRadius: tree ? "50%" : 12, color: "#f4efe4", fontSize: 11, width: tree ? 92 : 180, height: tree ? 64 : undefined, padding: 10 } })), [spec.nodes, tree]);
  const edges = useMemo(() => spec.edges.map((edge, index) => ({ id: `e-${index}`, source: edge.source, target: edge.target, label: edge.label, animated: !tree, markerEnd: { type: MarkerType.ArrowClosed }, style: { stroke: tree ? "#75ad8d" : "#df9a62" }, labelStyle: { fill: "#b8c6bc", fontSize: 9 } })), [spec.edges, tree]);
  return <div className="network-canvas"><ReactFlow nodes={nodes} edges={edges} fitView minZoom={.35} maxZoom={1.8} nodesConnectable={false} onNodeClick={(_, node) => setSelected(node.data)}><Background color="#486555" gap={22} size={1} /><MiniMap pannable zoomable nodeColor={tree ? "#75ad8d" : "#df9a62"} /><Controls showInteractive={false} /></ReactFlow>{selected && <button className="node-popover" type="button" onClick={() => setSelected(null)}><strong>{selected.label}</strong><span>{selected.description}</span></button>}</div>;
}
function NeuralNetwork({ spec }) {
  const layers = spec.data?.layers || []; const [active, setActive] = useState([0, 0]); const widthStep = 600 / Math.max(layers.length - 1, 1);
  return <div className="neural-lab"><svg viewBox="0 0 760 320" role="img" aria-label="Interactive neural network">{layers.slice(0, 6).map((layer, li) => Array.from({ length: Math.min(Number(layer.nodes) || 1, 8) }).map((_, ni) => { const x = 80 + li * widthStep; const count = Number(layer.nodes) || 1; const y = 55 + ni * (210 / Math.max(count - 1, 1)); if (li === layers.length - 1) return null; const next = layers[li + 1]; return Array.from({ length: Math.min(Number(next.nodes) || 1, 8) }).map((__, nni) => <line key={`${li}-${ni}-${nni}`} x1={x} y1={y} x2={80 + (li + 1) * widthStep} y2={55 + nni * (210 / Math.max((Number(next.nodes) || 1) - 1, 1))} className={active[0] === li && active[1] === ni ? "is-active" : ""} />); }))}{layers.slice(0, 6).map((layer, li) => <g key={layer.label}>{Array.from({ length: Math.min(Number(layer.nodes) || 1, 8) }).map((_, ni) => { const x = 80 + li * widthStep; const y = 55 + ni * (210 / Math.max((Number(layer.nodes) || 1) - 1, 1)); return <circle key={ni} cx={x} cy={y} r="13" className={active[0] === li && active[1] === ni ? "is-active" : ""} onClick={() => setActive([li, ni])} />; })}<text x={80 + li * widthStep} y="300" textAnchor="middle">{layer.label}</text></g>)}</svg></div>;
}
function MathVisual({ spec }) {
  if (spec.data_points?.length) return <div className="math-chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={spec.data_points}><CartesianGrid stroke="rgba(244,239,228,.08)" /><XAxis dataKey="label" stroke="#93a397" /><YAxis stroke="#93a397" /><Tooltip contentStyle={{ background: "#10201a", border: "1px solid #c97d4a" }} /><Line dataKey="value" stroke="#e2a06a" strokeWidth={3} dot={{ r: 5, fill: "#f4efe4" }} /></LineChart></ResponsiveContainer></div>;
  const matrix = spec.data?.matrix || [[1, 2], [3, 4]]; const vector = spec.data?.vector;
  return <div className="math-lab"><div className="matrix">{matrix.map((row, index) => <div key={index}>{row.map((value, cell) => <button type="button" key={cell}>{value}</button>)}</div>)}</div>{vector && <><span>×</span><div className="vector">{vector.map((value, index) => <i key={index}>{value}</i>)}</div></>}<div className="axis"><i /><b style={{ transform: `translate(${(vector?.[0] || 2) * 18}px,${-(vector?.[1] || 1) * 18}px)` }} /></div></div>;
}
function Timeline({ spec }) { const state = usePlayback(spec.steps.length); return <div className="timeline-lab"><div className="timeline-line">{spec.steps.map((item, index) => <button type="button" className={index === state.step ? "is-active" : ""} onClick={() => state.setStep(index)} key={`${item.title}-${index}`}><i /><strong>{item.title}</strong></button>)}</div><div className="timeline-focus"><strong>{spec.steps[state.step]?.title}</strong><span>{spec.steps[state.step]?.description}</span></div><Player state={state} length={spec.steps.length} /></div>; }
function Comparison({ spec }) { const [expanded, setExpanded] = useState(null); const sides = spec.data?.sides || []; return <div className="comparison-lab">{sides.slice(0, 2).map((side, si) => <section key={side.title}><h4>{side.title}</h4>{(side.items || []).slice(0, 6).map((item, index) => <button type="button" onClick={() => setExpanded(expanded === `${si}-${index}` ? null : `${si}-${index}`)} className={expanded === `${si}-${index}` ? "is-active" : ""} key={index}><i>✓</i><span>{item}</span></button>)}</section>)}</div>; }
function CodeExecution({ spec }) { const state = usePlayback(spec.steps.length); const current = spec.steps[state.step] || {}; const lines = spec.data?.code_lines || []; return <div className="code-lab"><pre>{lines.map((line, index) => <code className={index + 1 === current.code_line ? "is-active" : ""} key={index}><span>{index + 1}</span>{line}</code>)}</pre><aside><small>Program state</small>{Object.entries(current.variables || {}).map(([key, value]) => <div key={key}><strong>{key}</strong><span>{String(value)}</span></div>)}<p>{current.description}</p></aside><Player state={state} length={spec.steps.length} /></div>; }
function Illustration({ spec }) { return <div className="illustration-lab"><div className="illustration-scene" aria-hidden="true"><i /><i /><i /><span /><b /></div><button type="button" disabled>Image-generation API placeholder</button><small>{spec.illustration_prompt}</small></div>; }

export default function VisualRenderer({ spec, visualOnly = false }) {
  const [explain, setExplain] = useState(false); let visual;
  if (spec.visual_type === "algorithm") visual = <Algorithm spec={spec} />; else if (spec.visual_type === "process") visual = <Process spec={spec} />; else if (spec.visual_type === "architecture") visual = <NetworkCanvas spec={spec} />; else if (spec.visual_type === "tree_graph") visual = <NetworkCanvas spec={spec} tree />; else if (spec.visual_type === "neural_network") visual = <NeuralNetwork spec={spec} />; else if (spec.visual_type === "math") visual = <MathVisual spec={spec} />; else if (spec.visual_type === "timeline") visual = <Timeline spec={spec} />; else if (spec.visual_type === "comparison") visual = <Comparison spec={spec} />; else if (spec.visual_type === "code_execution") visual = <CodeExecution spec={spec} />; else visual = <Illustration spec={spec} />;
  return <section className={`learning-visual ${visualOnly ? "is-prominent" : ""}`}><header><div><span>{spec.visual_type.replaceAll("_", " ")}</span><h3>{spec.title}</h3><p>{spec.summary}</p></div><em>{spec.teaching_strategy}</em></header><div className="notice-strip"><b>Notice</b><span>{spec.notice}</span></div>{visual}<footer><div><b>Takeaway</b><span>{spec.takeaway}</span></div>{spec.notice && <button type="button" onClick={() => setExplain((value) => !value)}>Explain this</button>}</footer>{explain && <div className="explain-panel">{spec.notice}</div>}</section>;
}
